### ISSUE TITLE
Min / Max values

### ISSUE THREAD

**Issue by Gisbert1** [bagges/deye-esp32-bridge#12]
Hi Markus,
I'm wondering why the range of min_value and max_value is sometimes very large and doesn't make sense physically. Is there a reason for this or can I change the values ​​to something that makes sense. On the other hand, I don't want to cause any damage to my DEYE and my battery, so I'd rather ask before I do any nonsense.
Then another question. At Time point 1 start (etc.) there is a slider. Here I would prefer a box with min and max values. How can I implement this?
Best regards
Gisbert

**Comment by bagges** [comment]
Which min/max values do you mean?

Slider to box can be changed with "mode": https://developers.home-assistant.io/docs/core/entity/number/#properties
