### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Gisbert1** [bagges/deye-esp32-bridge#13]
Hi Markus,
when I started an update of the file "deye-esp32-bridge-pace.yaml" I got the following respond: "Update Failed: Wrong Magic Byte". The only change was in line 11:
modbus_update_interval: "8s" instead of modbus_update_interval: "10s" which I have currently.
What is the right way to update changes to the ESP32?
Best Regards
Gisbert

**Comment by bagges** [comment]
Revert the changes and try again. your change seems correct.
