### ISSUE TITLE
ESP "redet" nicht mit dem BMS

### ISSUE THREAD

**Issue by ThiloGa** [bagges/deye-esp32-bridge#17]
Moin,

nachdem dann doch noch meine Zellen angekommen sind, konnte ich den Akku endlich in Betrieb nehmen.

Normales Netzwerkkabel in die RS485-1 und auf die Platine....
Keine Werte :-)
Laut den LEDs auf dem RS485 Chip wird auch nicht miteinander "geredet"
Es leuchtet regelmässig einmal kurz die TX. BMS scheint sich nicht angesprochen zu fühlen.

DIPs alle auf aus.

Ein zu Testzwecken weiterer angesteckter ESP mit RS485 nur mit dem code von syssi bestückt
(https://github.com/syssi/esphome-seplos-bms) läuft.

Any hint?

**Comment by bagges** [comment]
Überprüfe mal die Baud. Bei syssi ist diese auf 9600 und in meinem Beispiel auf 19200. Ändere den Wert mal ab.

**Comment by bagges** [comment]
Ja, ich selbst habe nur ein seplos v2. Über einen PR mit v3 Anpassungen würde ich mich freuen.
Der neey Code hat bei mir nicht mehr dazu gepasst.

**Comment by ThiloGa** [comment]
> Ja, ich selbst habe nur ein seplos v2. Über einen PR mit v3 Anpassungen würde ich mich freuen. Der neey Code hat bei mir nicht mehr dazu gepasst.

Code mergen ging eigentlich, passt ohne webserver und mqtt locker rein... PR mache ich noch

Allerdings tuts mit deiner Platine komische Dinge. Hab hier hin und her debuggt. Leider kann ich mir absolut keinen Reim drauf machen.

Gröbstes Problem (mit zwei Platinen getestet):

Deye und Seplos sind direkt verbunden. 
Stecke ich die Platine ohne Spannungsversorgung (!) mit einem vollbestücktem Netzwerkkabel an den RS485-1
reisst die direkte CAN-Verbindung mit W31 Battery com.. ab.

Da scheint irgendwas gewaltig rein zustören. Bin im Moment ernsthaft ratlos.

**Comment by bagges** [comment]
> > Ja, ich selbst habe nur ein seplos v2. Über einen PR mit v3 Anpassungen würde ich mich freuen. Der neey Code hat bei mir nicht mehr dazu gepasst.
> 
> Code mergen ging eigentlich, passt ohne webserver und mqtt locker rein... PR mache ich noch
> 
> Allerdings tuts mit deiner Platine komische Dinge. Hab hier hin und her debuggt. Leider kann ich mir absolut keinen Reim drauf machen.
> 
> Gröbstes Problem (mit zwei Platinen getestet):
> 
> Deye und Seplos sind direkt verbunden. Stecke ich die Platine ohne Spannungsversorgung (!) mit einem vollbestücktem Netzwerkkabel an den RS485-1 reisst die direkte CAN-Verbindung mit W31 Battery com.. ab.
> 
> Da scheint irgendwas gewaltig rein zustören. Bin im Moment ernsthaft ratlos.

Da CAN eigentlich nur durchgeschleift wird ohne sonstige Verbindung zum PCB kann ich mir das nicht erklären. Hast du mal geschaut ob vllt irgendwo ne Brücke hast am RJ45?

**Comment by ThiloGa** [comment]
> Da CAN eigentlich nur durchgeschleift wird ohne sonstige Verbindung zum PCB kann ich mir das nicht erklären. Hast du mal geschaut ob vllt irgendwo ne Brücke hast am RJ45?

Da auf dem PCB ja fast nix statt findet, bin ich so irritiert… :-)
Brücke möchte ich ausschließen, da 
1. ich das Problem bei zwei PCBs habe
2. Der CAN-Verbindungsabruch Deye/Seplos bei direkter Verbindung (keine Durchschleifung PCB), Netzwerkkabel in _spannungsfreiem_ PCB und Seplos statt findet. Daher eher mein Gedanke, dass PCB und Kabel irgendwie Antenne spielen und damit den Seplos stören. 
(Und ja, ich habe verschiedene Kabel(-Längen) benutzt. :-O

Hab mir mal ein 2 adriges Kabel gecrimpt -> läuft :-)
Verstehen kann ich es nicht. 

Ne Idee?

Grüsse

PS: Danke für die PCB Files… ;-)
PPS: Vielleicht solltest Du die Infos bei Dir um V2 ergänzen, dass nicht noch andere mit V3 einfach das yaml übernehmen.
