### ISSUE TITLE
PCB Board

### ISSUE THREAD

**Issue by Gisbert1** [bagges/deye-esp32-bridge#2]
Hi,
where can I order a PCB (designed with easyeda and produced by jlcpcb) or get the files to Order it myself?
Best Regards
Gisbert

**Comment by Gisbert1** [comment]
I found Gerber files in the source code. I believe that's what I'm looking for.

**Comment by bagges** [comment]
I do not sell the board. You can order from jlcpcb with the gerber files from the repo
