### ISSUE TITLE
Gehäuse, welche Schrauben sind da vorgesehen?

### ISSUE THREAD

**Issue by ThiloGa** [bagges/deye-esp32-bridge#20]
Kein Code issue... :-)

welche Schrauben sollen eigentlich das Case zusammenhalten?

Hab in meiner grossen Schraubenkiste nix passendes gefunden... ;-)

Grüsse
Thilo

**Comment by S-t-e-p-s-i** [comment]
Hallo Thilo,

nach meinem Verständnis kannst du da Gewindebuchsen einpressen schau mal bei Amazon und Co nach Ruthex Gewindebuchsen für 3D Druck. So mache ich das zumindest bei meinen Teilen die auch länger halten sollen.

[ruthex](https://www.ruthex.de/)

Gruß Stefan

**Comment by bagges** [comment]
Wie Stefan schon sagt. Ich nutze diese: https://amzn.eu/d/4xWvvk3 und schmelze sie mit dem Lötkolben ein.

**Comment by ThiloGa** [comment]
Hi Stefan,

> nach meinem Verständnis kannst du da Gewindebuchsen einpressen schau mal bei Amazon und Co nach Ruthex Gewindebuchsen für 3D Druck. So mache ich das zumindest bei meinen Teilen die auch länger halten sollen.

Danke für die Infos. Was zum 3D-Druck gelernt.

> 
> [ruthex](https://www.ruthex.de/)

Jetzt gibts da nur so grosse PE, brauche nur die 4 Stück.

Gibts ne Möglichkeit, dass du mir ein paar gegen Unkostenerstattung in einen Umschlag steckst?

Grüsse
Thilo

**Comment by bagges** [comment]
@ThiloGa Schick mir n Euro über den Donate Button und ich schick dir n paar zu. Schreib deine Adresse ins Kommentarfeld.
