### ISSUE TITLE
Log: Time	level	Tag	Message

### ISSUE THREAD

**Issue by Gisbert1** [bagges/deye-esp32-bridge#6]
Hello Markus,

I receive in the Webbrowser all the time logs like the following:

Time	level	Tag	Message
17:43:50	[W]	[component:205]	
Components should block for at most 20-30ms.
17:43:51	[W]	[component:204]	
Component modbus_controller took a long time for an operation (0.10 s).
17:43:51	[W]	[component:205]	
Components should block for at most 20-30ms.
17:43:51	[W]	[component:204]	
Component modbus_controller took a long time for an operation (0.06 s).
17:43:51	[W]	[component:205]	
Components should block for at most 20-30ms.
17:43:59	[W]	[component:204]	
Component modbus_controller took a long time for an operation (0.08 s).

As I use MQTT (and currently do not know how to connect ESPHome with my house automation FHEM), I'm fine with the selected small numbers of topics of about 25 messages with each update - I use 10 seconds between each update. My MQTT broker has irregular connection issues which is very likely not connected to this project.

In the web browser it's possible to set values or select on/off. It would be helpfull for me if I could also publish MQTT Messages to the ESP32. Is there a simple way to implement that to your code, to receive messages in the ESP32 and set values or switch on/off?

Regards
Gisbert

**Comment by bagges** [comment]
You could create a subscribe sensor (https://esphome.io/components/sensor/mqtt_subscribe.html) and then do an automation with on_value, check the value and push it to your desired action.
